### ISSUE TITLE
List properties used to evaluate single/all flags

### ISSUE THREAD

**Issue by oxddr** [open-feature/protocol#18]
Add API method that returns properties (property = field in the evaluation context) used to evaluate single/all flags. The OFREP client then can only calculate and send properties, which are used by given flags. 

Some properties are expensive to calculate (e.g. they require separate, expensive RPC) and we'd like to avoid calculating them if possible. With the protocol in the current shape, it's not possible.

**Comment by oxddr** [comment]
That's correct - property = field in the evaluation context. I've updated the top-level description.

**Comment by thomaspoignant** [comment]
If I understand correctly, you would like a way to know which fields of the evaluation context each flag is using?
Something like :
```
- flag1: name, targetingKey, company
- flag2: age, targetingKey
- flag3: city, country
- ...
```

This is an interesting use case, I don't know if any vendors are doing this.
@beeme1mr @toddbaert have you heard about something like this?

**Comment by thomaspoignant** [comment]
@oxddr do you expect some validation in the provider based on that? Just trying to understand what would be the scope of this feature if we decide to implement it.

**Comment by beeme1mr** [comment]
Hey @oxddr, could you please elaborate on how this would work? How would this information be returned to the service so that it could be used to avoid expensive async calls? How would changes to the flag definition (e.g. a new property is added to a rule) be communicated to the provider?

Vendors would have access to this information in the ruleset, but I haven't seen many expose it. I've thought about using this information for reporting purposes in the past. It's an interesting use case that we'll have to consider the end-to-end ramifications.

**Comment by grimly** [comment]
This looks like a key metadata endpoint.

To that effect, I would propose an extension specification that extends the configuration response with a `keyMetadataEndpoint` property.
Its value, if present, must be a URI.
Its resolution should grant all key metadata. I propose this kind of format :

```yaml
---
keys:
  my-flag-a:
    dependencies:
      # List of Json Pointers (RFC 6901) this flag depends on
      # If between a change in your context, the value of one of these pointers is not equal to its previous value, then the key is invalid
      # Equality would be described the same as JSONPatch "test" operation ( https://datatracker.ietf.org/doc/html/rfc6902#section-4.6 ) or JSON Schema instance equality ( https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-instance-equality )
      - /email
      - /language
    schema: # As a bonus, you could verify the flag has the type you expect
      type: boolean
  I.love.dotted.flag.names:
    dependencies: [] # Flags could just be set without dependency by the service
    schema:
      type: string
  and/slashed/ones:
    # a missing dependencies key could mean it depends on everything. Or maybe it's not obvious and we should rather remove it
    schema:
      type: integer
      format: int32
  "and also spaces because the spec do not forbid them":
    description: |
      Keys could have descriptions attached for documentation. That's out of the scope of your request but I'd like that :)
    dependencies:
      - / # You could depend on just everything by its pointer
    schema: # As a bonus, you could verify the flag has the type you expect
      type: boolean
```

Some notes on my format proposal:

* This is YAML because I'm lazy.
* I'm bad at naming things
* I though of using a `/context` prefix to account for the possibility of taking into account other request parameters such as a claim from a JWT in the `Authorization` header.
